load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_img//img:image.bzl", "image_manifest")
load("@rules_img//img:layer.bzl", "image_layer")
load("@rules_img//img:load.bzl", "image_load")
load("@rules_img//img:push.bzl", "image_push")

go_library(
    name = "embedd_lib",
    srcs = ["embedd.go"],
    importpath = "github.com/teapotovh/teapot/cmd/embedd",
    visibility = ["//visibility:private"],
    deps = [
        "//lib/grpcsrv",
        "//lib/log",
        "//lib/observability",
        "//lib/run",
        "//service/embed",
        "@com_github_spf13_pflag//:pflag",
    ],
)

go_binary(
    name = "embedd",
    embed = [":embedd_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "lib",
    srcs = ["embedd.go"],
    importpath = "",
    visibility = ["//visibility:private"],
    deps = [
        "//lib/httpsrv",
        "//lib/log",
        "//lib/observability",
        "//lib/run",
        "//service/embed",
        "@com_github_spf13_pflag//:pflag",
    ],
)

# OCI Image building
image_layer(
    name = "binary_layer",
    srcs = {
        "/embedd": ":embedd",
    },
    compress = "zstd",
)

image_layer(
    name = "onnx_layer",
    srcs = {
        "/lib/libonnxruntime.so": "@onnxruntime_prebuilt//:lib",
    },
)

image_manifest(
    name = "image",
    base = "@distroless_cc_debian13",
    entrypoint = ["/embedd"],
    layers = [
        ":binary_layer",
        ":onnx_layer",
    ],
)

image_load(
    name = "load",
    image = ":image",
    tag = "ghcr.io/teapotovh/embedd:latest",
)

image_push(
    name = "push",
    image = ":image",
    registry = "ghcr.io",
    repository = "teapotovh/embedd",
    stamp = "disabled",
    tag_file = "//bazel:version_file_latest",
)

image_push(
    name = "push_ttl",
    image = ":image",
    registry = "ocihub.com",
    repository = "teapotovh_embedd",
    tag = "1h",
)
