version: "2"
run:
  go: "1.24"
  tests: true
linters:
  enable:
    - gocyclo
    - revive
    - sloglint
  disable:
    - depguard
    - dupl
  settings:
    errcheck:
      exclude-functions:
        - (*testing.T).Error
        - (*testing.T).Fatal
        - (*testing.T).Fatalf
        - (*testing.T).Log
        - (*testing.T).Logf
        - (*testing.T).Errorf
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          severity: warning
    sloglint:
      kv-only: true
      no-global: all
      static-msg: true
      key-naming-case: snake
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/teapotovh)
        - blank
      no-inline-comments: true
      no-prefix-comments: true
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    golines:
      max-len: 120
      shorten-comments: true
      reformat-tags: false
