version: "2"
run:
  go: "1.24"
  tests: true
linters:
  enable:
    - gocyclo
    - revive
    - sloglint
    - modernize
    - staticcheck
    - govet
    - errcheck
    - gosec
    - misspell
    - unconvert
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - embeddedstructfieldcheck
    # - err113 # nice to have, requires some work
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    # - funcorder # nice to have, requires some work
    - gochecknoinits
    - gochecksumtype
    - goconst
    # - gocritic # very verbose and minor improvements
    - godot
    - godox
    - iface
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - iotamixing
    # - ireturn # nice to have, requires some ignores
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - protogetter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    # - wrapcheck # nice to have, requires some work
    - wsl_v5
  settings:
    # ireturn:
    #   allow:
    #     - anon
    #     - error
    #     - empty
    #     - stdlib
    #     - generic
    #     - (Node)$
    errcheck:
      exclude-functions:
        - (*testing.T).Error
        - (*testing.T).Fatal
        - (*testing.T).Fatalf
        - (*testing.T).Log
        - (*testing.T).Logf
        - (*testing.T).Errorf
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: true
    sloglint:
      kv-only: true
      no-global: all
      static-msg: true
      key-naming-case: snake
    staticcheck:
      checks:
        - all
        # Disable: Incorrect or missing package comment
        # See: https://staticcheck.dev/docs/checks/#ST1000
        - "-ST1000"
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/teapotovh)
        - blank
      no-inline-comments: true
      no-prefix-comments: true
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    golines:
      max-len: 120
      shorten-comments: true
      reformat-tags: false
