load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "release_lib",
    srcs = ["release.go"],
    importpath = "github.com/teapotovh/teapot/tools/release",
    visibility = ["//visibility:private"],
    deps = ["@rules_go//go/runfiles"],
)

go_binary(
    name = "release",
    data = [
        "//tools:gazelle",
        "@multitool//tools/buildifier",
        "@multitool//tools/golangci-lint",
    ],
    embed = [":release_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "lib",
    srcs = ["release.go"],
    importpath = "",
    visibility = ["//visibility:private"],
    deps = ["@rules_go//go/runfiles"],
)
