load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "buildcheck_lib",
    srcs = ["buildcheck.go"],
    importpath = "github.com/teapotovh/teapot/tools/buildcheck",
    visibility = ["//visibility:private"],
    deps = ["@rules_go//go/runfiles"],
)

go_binary(
    name = "buildcheck",
    data = [
        "//tools:gazelle",
        "@multitool//tools/buildifier",
    ],
    embed = [":buildcheck_lib"],
    visibility = ["//visibility:public"],
)
