// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.1
// source: proto/embed/embed.proto

package embed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_proto_embed_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embed_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_proto_embed_embed_proto_rawDescGZIP(), []int{0}
}

func (x *Embedding) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Embedding) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedPassageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedPassageRequest) Reset() {
	*x = EmbedPassageRequest{}
	mi := &file_proto_embed_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedPassageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedPassageRequest) ProtoMessage() {}

func (x *EmbedPassageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embed_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedPassageRequest.ProtoReflect.Descriptor instead.
func (*EmbedPassageRequest) Descriptor() ([]byte, []int) {
	return file_proto_embed_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedPassageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedPassageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedPassageResponse) Reset() {
	*x = EmbedPassageResponse{}
	mi := &file_proto_embed_embed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedPassageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedPassageResponse) ProtoMessage() {}

func (x *EmbedPassageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embed_embed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedPassageResponse.ProtoReflect.Descriptor instead.
func (*EmbedPassageResponse) Descriptor() ([]byte, []int) {
	return file_proto_embed_embed_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedPassageResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type EmbedQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedQueryRequest) Reset() {
	*x = EmbedQueryRequest{}
	mi := &file_proto_embed_embed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedQueryRequest) ProtoMessage() {}

func (x *EmbedQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embed_embed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedQueryRequest.ProtoReflect.Descriptor instead.
func (*EmbedQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_embed_embed_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedQueryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     *Embedding             `protobuf:"bytes,1,opt,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedQueryResponse) Reset() {
	*x = EmbedQueryResponse{}
	mi := &file_proto_embed_embed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedQueryResponse) ProtoMessage() {}

func (x *EmbedQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embed_embed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedQueryResponse.ProtoReflect.Descriptor instead.
func (*EmbedQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_embed_embed_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedQueryResponse) GetEmbedding() *Embedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_proto_embed_embed_proto protoreflect.FileDescriptor

const file_proto_embed_embed_proto_rawDesc = "" +
	"\n" +
	"\x17proto/embed/embed.proto\x12\x05embed\"7\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\")\n" +
	"\x13EmbedPassageRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"H\n" +
	"\x14EmbedPassageResponse\x120\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x10.embed.EmbeddingR\n" +
	"embeddings\"'\n" +
	"\x11EmbedQueryRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"D\n" +
	"\x12EmbedQueryResponse\x12.\n" +
	"\tembedding\x18\x01 \x01(\v2\x10.embed.EmbeddingR\tembedding2\x9a\x01\n" +
	"\bEmbedder\x12I\n" +
	"\fEmbedPassage\x12\x1a.embed.EmbedPassageRequest\x1a\x1b.embed.EmbedPassageResponse\"\x00\x12C\n" +
	"\n" +
	"EmbedQuery\x12\x18.embed.EmbedQueryRequest\x1a\x19.embed.EmbedQueryResponse\"\x00B/Z-github.com/teapotovh/teapot/proto/embed;embedb\x06proto3"

var (
	file_proto_embed_embed_proto_rawDescOnce sync.Once
	file_proto_embed_embed_proto_rawDescData []byte
)

func file_proto_embed_embed_proto_rawDescGZIP() []byte {
	file_proto_embed_embed_proto_rawDescOnce.Do(func() {
		file_proto_embed_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_embed_embed_proto_rawDesc), len(file_proto_embed_embed_proto_rawDesc)))
	})
	return file_proto_embed_embed_proto_rawDescData
}

var file_proto_embed_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_embed_embed_proto_goTypes = []any{
	(*Embedding)(nil),            // 0: embed.Embedding
	(*EmbedPassageRequest)(nil),  // 1: embed.EmbedPassageRequest
	(*EmbedPassageResponse)(nil), // 2: embed.EmbedPassageResponse
	(*EmbedQueryRequest)(nil),    // 3: embed.EmbedQueryRequest
	(*EmbedQueryResponse)(nil),   // 4: embed.EmbedQueryResponse
}
var file_proto_embed_embed_proto_depIdxs = []int32{
	0, // 0: embed.EmbedPassageResponse.embeddings:type_name -> embed.Embedding
	0, // 1: embed.EmbedQueryResponse.embedding:type_name -> embed.Embedding
	1, // 2: embed.Embedder.EmbedPassage:input_type -> embed.EmbedPassageRequest
	3, // 3: embed.Embedder.EmbedQuery:input_type -> embed.EmbedQueryRequest
	2, // 4: embed.Embedder.EmbedPassage:output_type -> embed.EmbedPassageResponse
	4, // 5: embed.Embedder.EmbedQuery:output_type -> embed.EmbedQueryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_embed_embed_proto_init() }
func file_proto_embed_embed_proto_init() {
	if File_proto_embed_embed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_embed_embed_proto_rawDesc), len(file_proto_embed_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_embed_embed_proto_goTypes,
		DependencyIndexes: file_proto_embed_embed_proto_depIdxs,
		MessageInfos:      file_proto_embed_embed_proto_msgTypes,
	}.Build()
	File_proto_embed_embed_proto = out.File
	file_proto_embed_embed_proto_goTypes = nil
	file_proto_embed_embed_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmbedderClient is the client API for Embedder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmbedderClient interface {
	EmbedPassage(ctx context.Context, in *EmbedPassageRequest, opts ...grpc.CallOption) (*EmbedPassageResponse, error)
	EmbedQuery(ctx context.Context, in *EmbedQueryRequest, opts ...grpc.CallOption) (*EmbedQueryResponse, error)
}

type embedderClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbedderClient(cc grpc.ClientConnInterface) EmbedderClient {
	return &embedderClient{cc}
}

func (c *embedderClient) EmbedPassage(ctx context.Context, in *EmbedPassageRequest, opts ...grpc.CallOption) (*EmbedPassageResponse, error) {
	out := new(EmbedPassageResponse)
	err := c.cc.Invoke(ctx, "/embed.Embedder/EmbedPassage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embedderClient) EmbedQuery(ctx context.Context, in *EmbedQueryRequest, opts ...grpc.CallOption) (*EmbedQueryResponse, error) {
	out := new(EmbedQueryResponse)
	err := c.cc.Invoke(ctx, "/embed.Embedder/EmbedQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbedderServer is the server API for Embedder service.
type EmbedderServer interface {
	EmbedPassage(context.Context, *EmbedPassageRequest) (*EmbedPassageResponse, error)
	EmbedQuery(context.Context, *EmbedQueryRequest) (*EmbedQueryResponse, error)
}

// UnimplementedEmbedderServer can be embedded to have forward compatible implementations.
type UnimplementedEmbedderServer struct {
}

func (*UnimplementedEmbedderServer) EmbedPassage(context.Context, *EmbedPassageRequest) (*EmbedPassageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbedPassage not implemented")
}
func (*UnimplementedEmbedderServer) EmbedQuery(context.Context, *EmbedQueryRequest) (*EmbedQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbedQuery not implemented")
}

func RegisterEmbedderServer(s *grpc.Server, srv EmbedderServer) {
	s.RegisterService(&_Embedder_serviceDesc, srv)
}

func _Embedder_EmbedPassage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedPassageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedderServer).EmbedPassage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/embed.Embedder/EmbedPassage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedderServer).EmbedPassage(ctx, req.(*EmbedPassageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Embedder_EmbedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedderServer).EmbedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/embed.Embedder/EmbedQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedderServer).EmbedQuery(ctx, req.(*EmbedQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Embedder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "embed.Embedder",
	HandlerType: (*EmbedderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmbedPassage",
			Handler:    _Embedder_EmbedPassage_Handler,
		},
		{
			MethodName: "EmbedQuery",
			Handler:    _Embedder_EmbedQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/embed/embed.proto",
}
