// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: embed.proto

package embed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Embedding represents an embedding vector for a chunk of text
type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{0}
}

func (x *Embedding) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Embedding) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// EmbedRequest carries the request to run the embedding model on a long corpus,
// creating n embeddings based on chunking, with the configured overlap
// (hardcoded on the server side).
type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// EmbedReply contains the generated embedding and relative metadata.
type EmbedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedReply) Reset() {
	*x = EmbedReply{}
	mi := &file_embed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedReply) ProtoMessage() {}

func (x *EmbedReply) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedReply.ProtoReflect.Descriptor instead.
func (*EmbedReply) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedReply) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

// EmbedSingleRequest carries the request required to generate a single embedding
// from the model.
type EmbedSingleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedSingleRequest) Reset() {
	*x = EmbedSingleRequest{}
	mi := &file_embed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedSingleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedSingleRequest) ProtoMessage() {}

func (x *EmbedSingleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedSingleRequest.ProtoReflect.Descriptor instead.
func (*EmbedSingleRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedSingleRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// EmbedSingleReply carries the request required to generate a single embedding
// from the model.
type EmbedSingleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     *Embedding             `protobuf:"bytes,1,opt,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedSingleReply) Reset() {
	*x = EmbedSingleReply{}
	mi := &file_embed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedSingleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedSingleReply) ProtoMessage() {}

func (x *EmbedSingleReply) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedSingleReply.ProtoReflect.Descriptor instead.
func (*EmbedSingleReply) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedSingleReply) GetEmbedding() *Embedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_embed_proto protoreflect.FileDescriptor

const file_embed_proto_rawDesc = "" +
	"\n" +
	"\vembed.proto\x12\x05embed\"7\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\">\n" +
	"\n" +
	"EmbedReply\x120\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x10.embed.EmbeddingR\n" +
	"embeddings\"(\n" +
	"\x12EmbedSingleRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"B\n" +
	"\x10EmbedSingleReply\x12.\n" +
	"\tembedding\x18\x01 \x01(\v2\x10.embed.EmbeddingR\tembedding2\x82\x01\n" +
	"\bEmbedder\x121\n" +
	"\x05Embed\x12\x13.embed.EmbedRequest\x1a\x11.embed.EmbedReply\"\x00\x12C\n" +
	"\vEmbedSingle\x12\x19.embed.EmbedSingleRequest\x1a\x17.embed.EmbedSingleReply\"\x00B\bZ\x06/embedb\x06proto3"

var (
	file_embed_proto_rawDescOnce sync.Once
	file_embed_proto_rawDescData []byte
)

func file_embed_proto_rawDescGZIP() []byte {
	file_embed_proto_rawDescOnce.Do(func() {
		file_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embed_proto_rawDesc), len(file_embed_proto_rawDesc)))
	})
	return file_embed_proto_rawDescData
}

var file_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_embed_proto_goTypes = []any{
	(*Embedding)(nil),          // 0: embed.Embedding
	(*EmbedRequest)(nil),       // 1: embed.EmbedRequest
	(*EmbedReply)(nil),         // 2: embed.EmbedReply
	(*EmbedSingleRequest)(nil), // 3: embed.EmbedSingleRequest
	(*EmbedSingleReply)(nil),   // 4: embed.EmbedSingleReply
}
var file_embed_proto_depIdxs = []int32{
	0, // 0: embed.EmbedReply.embeddings:type_name -> embed.Embedding
	0, // 1: embed.EmbedSingleReply.embedding:type_name -> embed.Embedding
	1, // 2: embed.Embedder.Embed:input_type -> embed.EmbedRequest
	3, // 3: embed.Embedder.EmbedSingle:input_type -> embed.EmbedSingleRequest
	2, // 4: embed.Embedder.Embed:output_type -> embed.EmbedReply
	4, // 5: embed.Embedder.EmbedSingle:output_type -> embed.EmbedSingleReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_embed_proto_init() }
func file_embed_proto_init() {
	if File_embed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embed_proto_rawDesc), len(file_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embed_proto_goTypes,
		DependencyIndexes: file_embed_proto_depIdxs,
		MessageInfos:      file_embed_proto_msgTypes,
	}.Build()
	File_embed_proto = out.File
	file_embed_proto_goTypes = nil
	file_embed_proto_depIdxs = nil
}
