load("@rules_go//proto:compiler.bzl", "go_proto_compiler")

alias(
    name = "protoc-gen-go-vtproto",
    actual = "@com_github_planetscale_vtprotobuf//cmd/protoc-gen-go-vtproto",
    visibility = ["//visibility:private"],
)

go_proto_compiler(
    name = "go_vtproto",
    options = [
        "features=size+equal+marshal+unmarshal+unmarshal_unsafe+clone",
    ],
    plugin = "//proto:protoc-gen-go-vtproto",
    suffix = "_vtproto.pb.go",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_planetscale_vtprotobuf//protohelpers",
    ],
)
