load("@rules_go//proto:compiler.bzl", "go_proto_compiler")
load("@rules_go//go:def.bzl", "go_binary")

alias(
    name = "protoc-gen-go-vtproto",
    actual = "@com_github_planetscale_vtprotobuf//cmd/protoc-gen-go-vtproto",
    visibility = ["//visibility:private"],
)

go_proto_compiler(
    name = "go_vtproto",
    plugin = "//proto:protoc-gen-go-vtproto",
    suffix = ".vt.pb.go",
    options = [
        "features=marshal+unmarshal+size+equal+clone+grpc",
    ],
    visibility = ["//visibility:public"],
)

