# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "embed.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x65mbed.proto\x12\x05\x65mbed")\n\tEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x0c\n\x04text\x18\x02 \x01(\t"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"2\n\nEmbedReply\x12$\n\nembeddings\x18\x01 \x03(\x0b\x32\x10.embed.Embedding""\n\x12\x45mbedSingleRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"7\n\x10\x45mbedSingleReply\x12#\n\tembedding\x18\x01 \x01(\x0b\x32\x10.embed.Embedding2\x82\x01\n\x08\x45mbedder\x12\x31\n\x05\x45mbed\x12\x13.embed.EmbedRequest\x1a\x11.embed.EmbedReply"\x00\x12\x43\n\x0b\x45mbedSingle\x12\x19.embed.EmbedSingleRequest\x1a\x17.embed.EmbedSingleReply"\x00\x42\x08Z\x06/embedb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "embed_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\006/embed"
    _globals["_EMBEDDING"]._serialized_start = 22
    _globals["_EMBEDDING"]._serialized_end = 63
    _globals["_EMBEDREQUEST"]._serialized_start = 65
    _globals["_EMBEDREQUEST"]._serialized_end = 93
    _globals["_EMBEDREPLY"]._serialized_start = 95
    _globals["_EMBEDREPLY"]._serialized_end = 145
    _globals["_EMBEDSINGLEREQUEST"]._serialized_start = 147
    _globals["_EMBEDSINGLEREQUEST"]._serialized_end = 181
    _globals["_EMBEDSINGLEREPLY"]._serialized_start = 183
    _globals["_EMBEDSINGLEREPLY"]._serialized_end = 238
    _globals["_EMBEDDER"]._serialized_start = 241
    _globals["_EMBEDDER"]._serialized_end = 371
# @@protoc_insertion_point(module_scope)
