# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import proto.embed_pb2 as embed__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in embed_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EmbedderStub(object):
    """Embedder provides RPC calls to generate embeddings from text input."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
            "/embed.Embedder/Embed",
            request_serializer=embed__pb2.EmbedRequest.SerializeToString,
            response_deserializer=embed__pb2.EmbedReply.FromString,
            _registered_method=True,
        )
        self.EmbedSingle = channel.unary_unary(
            "/embed.Embedder/EmbedSingle",
            request_serializer=embed__pb2.EmbedSingleRequest.SerializeToString,
            response_deserializer=embed__pb2.EmbedSingleReply.FromString,
            _registered_method=True,
        )


class EmbedderServicer(object):
    """Embedder provides RPC calls to generate embeddings from text input."""

    def Embed(self, request, context):
        """Embed takes a sentence and returns its embedding computed according to
        the selected model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EmbedSingle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EmbedderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Embed": grpc.unary_unary_rpc_method_handler(
            servicer.Embed,
            request_deserializer=embed__pb2.EmbedRequest.FromString,
            response_serializer=embed__pb2.EmbedReply.SerializeToString,
        ),
        "EmbedSingle": grpc.unary_unary_rpc_method_handler(
            servicer.EmbedSingle,
            request_deserializer=embed__pb2.EmbedSingleRequest.FromString,
            response_serializer=embed__pb2.EmbedSingleReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("embed.Embedder", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("embed.Embedder", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Embedder(object):
    """Embedder provides RPC calls to generate embeddings from text input."""

    @staticmethod
    def Embed(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/embed.Embedder/Embed",
            embed__pb2.EmbedRequest.SerializeToString,
            embed__pb2.EmbedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EmbedSingle(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/embed.Embedder/EmbedSingle",
            embed__pb2.EmbedSingleRequest.SerializeToString,
            embed__pb2.EmbedSingleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
