load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")

gazelle_binary(
    name = "gazelle_multilang",
    languages = [
        "@gazelle//language/go",
        "@gazelle//language/proto",
    ],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_multilang",
    visibility = ["//visibility:public"],
)

alias(
    name = "release",
    actual = "//tools/release",
)

alias(
    name = "golangci-lint",
    actual = "@multitool//tools/golangci-lint:workspace_root",
)

alias(
    name = "buildifier",
    actual = "@multitool//tools/buildifier:workspace_root",
)
