name: Verify Generated Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    name: Verify that generated files are up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Check build files
        run: bazel run //tools/buildcheck

      - name: Ensure no diffs
        run: |
          if ! git diff --exit-code; then
            echo "::error::Generated files are out of date."
            exit 1
          fi
